-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물
-- ID, 이름
-- ID 순으로 조회

SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID ASC;