-- 코드를 입력하세요
SELECT DATE_FORMAT(Z.SALES_DATE, '%Y-%m-%d') SALES_DATE,
Z.PRODUCT_ID, Z.USER_ID, Z.SALES_AMOUNT
FROM (SELECT USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE 
     UNION ALL 
      SELECT NULL, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE
     ) Z
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;